ventas/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'ventas'

urlpatterns = [
    path(_('carrito'), views.carrito, name='carrito'),
    path(_('eliminar-item/<int:id>'), views.eliminar_item, name='eliminar_item_carrito'),
    path(_('comprar'), views.comprar, name='comprar')
]

videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    # Include recibe el nombre de la aplicación .urls
    path(_('categorias/'),include('videojuego.urls_categoria')),
    path(_('videojuegos/'),include('videojuego.urls_videojuego')),
    path(_('usuarios/'),include('usuarios.urls')),
    path(_('articulos/'),include('articulos.urls')),
    path(_('ventas/'),include('ventas.urls')),
]   + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ventas/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User

class Venta(models.Model):
    usuario = models.ForeignKey(User, verbose_name=_("Usuario"), on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    pagada = models.BooleanField(_("Pagada"),default=False)

    class Meta:
        verbose_name = _('Venta')
        verbose_name_plural = _('Ventas')

class DetalleVenta(models.Model):
    articulo = models.ForeignKey("videojuego.Videojuego", verbose_name=_("Articulo"), on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(_("Cantidad"), default=1)
    precio = models.DecimalField(_("Precio"),max_digits=10, decimal_places=2)
    venta = models.ForeignKey("ventas.Venta",verbose_name=_(""), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Detalle de Venta')
        verbose_name_plural = _('Detalles de Venta')

ventas/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from videojuego.models import VideoJuego
from .models import Venta, DetalleVenta

@login_required
def carrito(request):
    articulos = request.session['articulos'] 
    carrito_vacio = True
   
    if len(articulos) > 0:
        carrito_vacio = False
    
    if request.method == "POST":
        id = request.POST.get('id')
        cantidad = int(request.POST.get('cantidad'))
        precio = float(request.POST.get('precio'))
        videojuego = get_object_or_404(VideoJuego, id=id)
        # Ya se encuentran artículos añadidos al carrito de ese producto.
        if id in request.session['articulos']:
            request.session['articulos'][id] = request.session['articulos'][id] + cantidad
            request.session['total'] = request.session['total'] + cantidad * precio
        # Aún no se había agregado ese artículo al carrito.
        else:
            request.session['articulos'][id] = cantidad
            request.session['total'] = request.session['total'] + cantidad * precio

        if videojuego.cantidad > 0:
            videojuego.cantidad = videojuego.cantidad - cantidad
            videojuego.save()

    lista_articulos = []
    for id in articulos:
        videojuego = get_object_or_404(VideoJuego, id=id)
        lista_articulos.append(videojuego)
        
    extra_context = {'carrito_vacio' : carrito_vacio,
                     'articulos' : lista_articulos}
    return render(request,'carrito/lista.html',extra_context)

@login_required
def eliminar_item(request, id):
    articulo_liberado = request.session['articulos'][str(id)]
    total = request.session['total']
    videojuego = get_object_or_404(VideoJuego, id=id)
    videojuego.cantidad = videojuego.cantidad + articulo_liberado
    videojuego.save()
    id_eliminar = str(videojuego.id)
    del request.session['articulos'][id_eliminar]
    total = total - float(videojuego.precio * articulo_liberado)
    total = request.session['total'] = total
    return redirect('ventas:carrito')

@login_required
def comprar(request):
    if request.method == "POST":
        venta = Venta()
        usuario = get_object_or_404(User, username=request.user.username)
        venta.usuario = usuario
        venta.pagada = True
        venta.save()

        for id in request.session['articulos']:
            detalle_venta = DetalleVenta()
            videojuego = get_object_or_404(VideoJuego, id=id)
            cantidad = request.session['articulos'][id]
            detalle_venta.articulo = videojuego
            detalle_venta.cantidad = cantidad
            detalle_venta.precio = cantidad * videojuego.precio
            detalle_venta.venta = venta
            detalle_venta.save()
        request.session['articulos'] = {}
        request.session['total'] = 0.0
        return redirect('articulos:lista')  

ventas/templates/carrito/lista.html
{% extends "dashboard_cliente.html" %}
{% load static %}

{% block titulo %}
    Carrito
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/extra.css' %}">
{% endblock %}

{% block contenido %}
    {% if request.session.articulos|length > 0 %}
        <h1 class="app-page-title">Artículos en el carrito</h1>
        <div class="app-card app-card-orders-table shadow-sm mb-5">
            <table class="table table-hover">
                <thead>
                    <th>Foto</th>
                    <th>Título</th>
                    <th>Año</th>
                    <th>Precio Unitario</th>
                    <th>Cantidad</th>
                    <th>Opciones</th>
                </thead>
                <tbody>
                    <form action="{% url 'ventas:comprar' %}" method="POST">
                        {% csrf_token %}
                        {% for articulo in articulos %}
                            <tr>
                                <td>
                                    <img alt="Sin imagen" width="110" height="150" src="{{MEDIA_URL}}{{articulo.foto}}">
                                </td>
                                <td>{{ articulo.titulo }}</td>
                                <td>{{ articulo.anio }}</td>
                                <td>${{ articulo.precio }}</td>
                                {% for id, cantidad in request.session.articulos.items %}
                                    {% if articulo.id|stringformat:'s' == id|stringformat:'s' %}
                                        <td>{{ cantidad }}</td>
                                    {% endif %}
                                {% endfor %}
                                <td><a href="{% url 'ventas:eliminar_item_carrito' articulo.id %}">Eliminar</a></td>
                            </tr>
                        {% endfor %}
                        <tr class="total">
                            <td>Total</td>
                            <td colspan="4"></td>
                            <td class="num">${{ request.session.total }}</td>
                        </tr>
                        <p class="text-right">
                            <input type="submit" class="btn btn-secondary" value="Confirmar compra">
                        </p>
                    </form>
                </tbody>
            </table>
        </div>
    {% else %}
        <h1 class="app-page-title">EL CARRITO ESTÁ VACÍO</h1>
    {% endif %}
 {% endblock %}