articulos/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'articulos'

urlpatterns = [
    path(_('lista/'),views.lista,name='lista'),
    path(_('detalle/<int:pk>'),views.detalle,name='detalle'),
]

ventas/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'ventas'

urlpatterns = [
    path(_('carrito'), views.carrito, name='carrito'),
    path(_('eliminar-item/<int:id>'), views.eliminar_item, name='eliminar_item_carrito'),
    path(_('comprar'), views.comprar, name='comprar')
]

videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    # Include recibe el nombre de la aplicación .urls
    path(_('categorias/'),include('videojuego.urls_categoria')),
    path(_('videojuegos/'),include('videojuego.urls_videojuego')),
    path(_('usuarios/'),include('usuarios.urls')),
    path(_('articulos/'),include('articulos.urls')),
    path(_('ventas/'),include('ventas.urls')),
]   + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/models.py
from django.db import models

# Create your models here.

articulos/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required

from videojuego.models import VideoJuego

@login_required
def lista(request):
    articulos = VideoJuego.objects.all()
    carrito_vacio = estado_carrito(request)
    extra_context = {'articulos' : articulos,
                     'carrito_vacio': carrito_vacio}
    return render(request,'lista.html', extra_context)

@login_required
def detalle(request,pk):
    articulo = VideoJuego.objects.get(id=pk)
    carrito_vacio = estado_carrito(request)
    extra_context = {'articulo' : articulo,
                     'carrito_vacio' : carrito_vacio}
    return render(request,'detalle.html', extra_context)

def estado_carrito(request):
    articulos = request.session['articulos']
    if len(articulos) > 0:
        return False
    else:
        return True

articulos/templates/dashboard_cliente.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>
        {% block titulo %}

        {% endblock titulo %}
    </title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">
    {% block css %}

    {% endblock css %}
</head> 

<body class="app">   	
    <header class="app-header fixed-top">	   	            
        <div class="app-header-inner">  
	        <div class="container-fluid py-2">
		        <div class="app-header-content"> 
		            <div class="row justify-content-between align-items-center">
			        
				    <div class="col-auto">
					    <a id="sidepanel-toggler" class="sidepanel-toggler d-inline-block d-xl-none" href="#">
						    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img"><title>{% translate "Menu" %}</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg>
					    </a>
				    </div><!--//col-->
		            <div class="search-mobile-trigger d-sm-none col">
			            <i class="search-mobile-trigger-icon fas fa-search"></i>
			        </div><!--//col-->
		            <div class="app-search-box col">
		                <form class="app-search-form">   
							<input type="text" placeholder="{% translate "Buscar" %}" name="search" class="form-control search-input">
							<button type="submit" class="btn search-btn btn-primary" value="Search"><i class="fas fa-search"></i></button> 
				        </form>
		            </div><!--//app-search-box-->
		            <div class="app-utilities col-auto">
						<a href="{% url 'ventas:carrito' %}"><img src="{% static 'images/carrito.png' %}" width="40" height="40">{% if carrito_vacio == False %}Ver carrito{% else %}Carrito vacío{% endif %}</a>
		            </div><!--//app-utilities-->
		        </div><!--//row-->
	            </div><!--//app-header-content-->
	        </div><!--//container-fluid-->
        </div><!--//app-header-inner-->
        <div id="app-sidepanel" class="app-sidepanel"> 
	        <div id="sidepanel-drop" class="sidepanel-drop"></div>
	        <div class="sidepanel-inner d-flex flex-column">
		        <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
		        <div class="app-branding">
		            <a class="app-logo" href="{% url 'articulos:lista' %}"><img class="logo-icon mr-2" src="{% static 'favicon.png' %}" alt="logo"><span class="logo-text">{% translate "TIENDA" %}</span></a>
	
		        </div><!--//app-branding-->  
	        </div><!--//sidepanel-inner-->
	    </div><!--//app-sidepanel-->
    </header><!--//app-header-->
    
    <div class="app-wrapper">
	    <div class="app-content pt-3 p-md-3 p-lg-4">
		    <div class="container-xl">
                {% block contenido %}

                {% endblock contenido %}
		    </div><!--//container-fluid-->
	    </div><!--//app-content-->
	    <footer class="app-footer">
		    <div class="container text-center py-3">
		         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
				 <div>
					<form action="{% url 'set_language' %}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="text" value="{{redirect_to}}">
						<select class="form-select" name="language" id="">
							{% get_available_languages as LANGUAGES %}
							{% get_language_info_list for LANGUAGES as languages %}
							{% for language in languages %}
								<option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
									{{language.name_local}} ({{language.code}})
								</option>
							{% endfor %}
						</select>
						<br>
						<input type="submit" class="btn app-btn-primary" value="{% translate "Seleccionar idioma" %}">
					</form>
				</div>
				 <div class="i18n" data-i18n="[html]content.body">
					<small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				</div>
		    </div>
	    </footer><!--//app-footer-->
    </div><!--//app-wrapper-->    					

    <!-- Javascript -->          
	<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
	
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  

    <!-- Charts JS -->
    <script src="{% static 'js/chart.min.js' %}"></script> 
    
    <!-- Page Specific JS -->
    <script src="{% static 'js/app.js' %}"></script>

    {% block js %}

    {% endblock js %} 
</body>
</html> 

articulos/templates/detalle.html
{% extends 'dashboard_cliente.html' %}
{% load static %}

{% block titulo %}
   Detalle del artículo
{% endblock %}

{% block contenido %}
    <h1>Detalle del artículo</h1>
    <div class="product-detail">
        <img class="image" alt="Sin imagen" width="280" height="411" src="{{MEDIA_URL}}{{articulo.foto}}">
        <h1>{{ articulo.titulo }}</h1>
        <p class="price">${{ articulo.precio }}</p>
        {{ articulo.descripcion|linebreaks }}
        {% if articulo.cantidad > 0 %}
            <form action="{% url 'ventas:carrito' %}" method="POST">
                {% csrf_token %}
                <div>
                    Cantidad:
                    <select name="cantidad">
                        {% if articulo.cantidad > 9 %}
                            {% for i in '123456789'|make_list %}
                                <option value="{{ forloop.counter }}" name="cantidad">{{ forloop.counter }}</option>
                            {% endfor %}
                        {% else %}
                            {% for i in articulo.cantidad|make_list %}
                                <option value="{{ forloop.counter }}" name="cantidad">{{ forloop.counter }}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <br>
                <input type="hidden" name="precio" value="{{articulo.precio}}">
                <input type="hidden" name="id" value="{{articulo.id}}">
                <input type="submit" class="btn btn-warning" value="Añadir al carrito">
            </form>
        {% else %}
            <h3>NO DISPONIBLE</h3>
        {% endif %}
    </div>
{% endblock %}

articulos/templates/lista.html
{% extends "dashboard_cliente.html" %}
{% load static %}

{% block titulo %}
    Artículos
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/extra.css' %}">
{% endblock %}

{% block contenido %}
{% if messages %}
		{% for mensaje in messages %}
			<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
				{{mensaje}}
			</div>
		{% endfor %}
{% endif %}
    <h1>Lista de artículos</h1>
    <div id="main" class="product-list">
        {% for articulo in articulos %}
            <div class="item">
                <div>
                    <a href="{% url 'articulos:detalle' articulo.id %}">
                        <img class="image" alt="Sin imagen" width="280" height="411" src="{{MEDIA_URL}}{{articulo.foto}}">
                    </a>
                </div>
                <a href="">{{ articulo.titulo }}</a><br>
                {{ articulo.anio }}
                <br>
                ${{ articulo.precio }}
                <br>
                {% if articulo.cantidad > 0 %}
                    <b>Stock: {{articulo.cantidad}}</b>
                {% else %}
                <b>NO DISPONIBLE</b>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}