usuarios/urls.py
from django.urls import path
# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views
from django.utils.translation import gettext_lazy as _

# Para que las urls puedan tener nombres parecidos 
# sin que haya mezcla de nombres
app_name = 'usuarios'

urlpatterns = [
    path(_('lista/'),views.UsuarioList.as_view(),name='lista'),
    path(_('nuevo/'),views.NuevoUsuario.as_view(), name='nuevo'),
    path(_('editar/<int:pk>'),views.UsuarioActualizar.as_view(),name='editar'),
    path(_('eliminar/<int:pk>'),views.UsuarioEliminar.as_view(),name='eliminar'),
    path(_('ver/<int:pk>'),views.UsuarioDetalle.as_view(),name='ver'),
    path(_('municipios/'),views.obtiene_municipios, name='municipio'),
    path(_('login/'),views.LoginUsuario.as_view(),name='login'),
    path(_('logout/'),views.logout,name='logout'),
    path(_('signup/'),views.SignUpUsuario.as_view(),name='signup'),
    path(_('activar/<slug:uid64>/<slug:token>'),views.ActivarCuenta.as_view(),name='activar'),
    path(_('modificar-grupos/<int:id>'),views.modificar_usuario_grupo,name='modificar_usuario_grupo'),
]

# eliminar/<int:id> Para indicar la recepción de un 
# argumento. Se indica el tipo de dato y el nombre.

ventas/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'ventas'

urlpatterns = [
    path(_('carrito'), views.carrito, name='carrito'),
    path(_('eliminar-item/<int:id>'), views.eliminar_item, name='eliminar_item_carrito'),
    path(_('comprar'), views.comprar, name='comprar')
]

videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    # Include recibe el nombre de la aplicación .urls
    path(_('categorias/'),include('videojuego.urls_categoria')),
    path(_('videojuegos/'),include('videojuego.urls_videojuego')),
    path(_('usuarios/'),include('usuarios.urls')),
    path(_('articulos/'),include('articulos.urls')),
    path(_('ventas/'),include('ventas.urls')),
]   + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import curp_validator, foto_validator
from django.utils.translation import gettext_lazy as _

class Usuario(User):
    curp = models.CharField(max_length = 18, validators = [curp_validator], blank=True, null=True)
    estado = models.ForeignKey("usuarios.Estado", verbose_name=_("Estado"), on_delete=models.CASCADE, blank=True, null=True)
    municipio = models.ForeignKey("usuarios.Municipio", verbose_name=_("Municipio"), on_delete=models.CASCADE, blank=True, null=True)
    foto = models.ImageField(_("Foto de perfil"), upload_to='perfiles', blank=True, null=True, validators=[foto_validator])

    class Meta:
        verbose_name = _('Usuario')
        verbose_name_plural = _('Usuarios')

class Estado(models.Model):
    nombre = models.CharField(max_length = 50)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Estado')
        verbose_name_plural = _('Estados')

class Municipio(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.ForeignKey("usuarios.Estado", verbose_name=_("Estado"), on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Municipio')
        verbose_name_plural = _('Municipios')

usuarios/forms.py
from django import forms 
from .models import Usuario
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

class UsuarioForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Usuario
        fields = ('username','password','email','first_name','last_name','curp','estado','municipio','foto')

        widgets = {
            'username' : forms.TextInput(attrs={'class' : 'form-control',
                                                'placeholder' : _('Crea un nombre de usuario')}),
            'password': forms.PasswordInput(attrs={'class': 'form-control',
                                                   'placeholder' : _('Crea una contraseña')}), 
            'email' : forms.EmailInput(attrs={'class' : 'form-control',
                                             'placeholder' : _('Indica tu correo electrónico')}), 
            'first_name' : forms.TextInput(attrs={'class' : 'form-control',
                                                    'placeholder' : _('Indica tu nombre')}),
            'last_name' : forms.TextInput(attrs={'class' : 'form-control',
                                                 'placeholder' : _('Indica tus apellidos')}),  
            'curp' : forms.TextInput(attrs={'class' : 'form-control',
                                            'placeholder' : _('Indica tu CURP')}),                                                                                              
            'estado' : forms.Select(attrs={'class':'form-control'}),
            'municipio' : forms.Select(attrs={'class':'form-control'}),
        }

    # Para guardar la contraseña de forma segura.
    def save(self, commit=True):
        user = super(UsuarioForm,self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class UsuarioRegistroForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ('username','password')

usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView, View
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.views import LoginView 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage 
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.contrib.auth.models import Group
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy

from .token import token_activacion
from .models import Usuario, Municipio, Estado
from .forms import UsuarioForm, UsuarioRegistroForm

class NuevoUsuario(PermissionRequiredMixin,CreateView):
    model = Usuario
    form_class = UsuarioForm
    permission_required = 'usuarios.add_usuario'
    extra_context = {'etiqueta' : gettext_lazy('Nuevo'),
    'boton' : gettext_lazy('Agregar'),
    'us_nuevo' : True}                
    success_url = reverse_lazy('usuarios:lista')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Toma el dominio actual. Es muy util para produccion
        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        # Le mandamos las variables requeridas en el formulario
        mensaje = render_to_string('confirmar_cuenta.html',
        {
            'usuario' : user,
            'dominio' : dominio,
            'uid' : uid,
            'token' : token
        }
        )
        asunto = _('Activar cuenta en el Sistema de Videojuegos')
        to = user.email
        # En el to se puede poner una lista de usuarios
        email = EmailMessage(
            asunto,
            mensaje,
            to=[to]
            )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)

class ActivarCuenta(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uid64'])
            token = kwargs['token']
            user = Usuario.objects.get(id=uid)
        except:
            user = None

        if user and token_activacion.check_token(user,token):
            user.is_active = True
            user.save()
            messages.success(self.request,_('¡Cuenta activada con éxito!'))
        else:
            messages.error(self.request,_('Token inválido, contacta al administrador'))
        
        return redirect('usuarios:login')


def obtiene_municipios(request):
    # estado = get_object_or_404(Estado, id=id_estado)
    if request.method == 'GET':
        return JsonResponse({'error':_('Petición incorrecta')}, safe=False, status=403)
    id_estado = request.POST.get('id')
    municipios = Municipio.objects.filter(estado_id=id_estado)
    json = []
    if not municipios:
        json.append({'error' : _('No se encontraron municipios con ese estado')})
    for municipio in municipios:
        json.append({'id' : municipio.id,
                     'nombre' : municipio.nombre})
    return JsonResponse(json, safe=False)

class UsuarioList(PermissionRequiredMixin,ListView):
    paginate_by = 5
    model = Usuario
    permission_required = 'usuarios.view_usuario'
    lista_grupos = Group.objects.all()

    extra_context = {'us_lista' : True,
                     'lista_grupos': lista_grupos}                
    template_name = 'usuarios:lista'

class UsuarioActualizar(PermissionRequiredMixin,UpdateView):
    model = Usuario
    permission_required = 'usuarios.change_usuario'
    form_class = UsuarioForm
    extra_context = {'etiqueta' : gettext_lazy('Editar'),
                     'boton' : gettext_lazy('Guardar')}
    success_url = reverse_lazy('usuarios:lista')

class UsuarioEliminar(PermissionRequiredMixin,DeleteView):
    model = Usuario
    permission_required = 'usuarios.delete_usuario'
    success_url = reverse_lazy('usuarios:lista')

class UsuarioDetalle(PermissionRequiredMixin,DetailView):
    model = Usuario
    permission_required = 'usuarios.view_usuario'

class LoginUsuario(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    
    def get_success_url(self):
        self.request.session['articulos'] = {}
        self.request.session['total'] = 0.0
        return super().get_success_url()

class SignUpUsuario(CreateView):
    template_name = 'signup.html'
    form_class = UsuarioForm
    success_url = reverse_lazy('usuarios:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Toma el dominio actual. Es muy util para produccion
        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        # Le mandamos las variables requeridas en el formulario
        mensaje = render_to_string('confirmar_cuenta.html',
        {
            'usuario' : user,
            'dominio' : dominio,
            'uid' : uid,
            'token' : token
        }
        )
        asunto = _('Activar cuenta en el Sistema de Videojuegos')
        to = user.email
        # En el to se puede poner una lista de usuarios
        email = EmailMessage(
            asunto,
            mensaje,
            to=[to]
            )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)

def logout(request):
    auth.logout(request)
    return redirect('usuarios:login')

def modificar_usuario_grupo(request,id):
    grupos = [grupo.id for grupo in Group.objects.all()]
    usuario = Usuario.objects.get(id=id)

    # El usuario tiene por lo menos un grupo asignado dado que en el arreglo
    # viene el token y algún grupo a asignar.
    if len(request.POST) > 1: 
        usuario.groups.clear()
        for item in request.POST:
            if request.POST[item] == 'on':
                usuario.groups.add(Group.objects.get(id=int(item)))
                
        messages.success(request, gettext_lazy(f'Se agregó al usuario {usuario} a los usuarios'))
    # El usuario no tiene ningún grupo asignado
    else:
        messages.error(request, gettext_lazy('El usuario debe pertenecer a un grupo como mínimo'))
    
    return redirect('usuarios:lista')

usuarios/templates/confirmar_cuenta.html
{% load i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% translate "Confirmar cuenta" %}</title>
    </head>
    <body>
        <div>
            <h3>{% translate "Validar cuenta" %}</h3>
            <p>{% translate "Hola"} {{usuario.username}}</p>
            <p> <!--Permite escapar elementos HTML en la traducción-->                
                Para completar tu registro en el sistema de <b>Videojuegos</b> debes dar click en el siguiente enlace: 
            </p>
            <br>
            <hr>
            <p>
                <a href="http://{{dominio}}{% url 'usuarios:activar' uid64=uid token=token %}">{% translate "Activar cuenta" %}</a>
            </p>
        </div>
    </body>
</html>

usuarios/templates/login.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>{% translate "Iniciar sesión" %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">
</head> 
<body class="app app-login p-0">    	
    {% if form.errors %}
        <div class="alert alert-warning">
            <p>{% translate "Usuario no encontrado" %}</p>
        </div>
    {% endif %}
	
	{% if messages %}
		{% for mensaje in messages %}
			<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}success{% endif %}">
				{{mensaje}}
			</div>
		{% endfor %}
	{% endif %}

    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5"> <!-- checkpoint -->
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="#"><img class="logo-icon mr-2" src="{% static 'favicon.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-5">{% translate "Inicio de sesión Sistema de Videojuegos" %}</h2>
			        <div class="auth-form-container text-left">
						<form class="auth-form login-form" method="POST">
                            {% csrf_token %}         
							<div class="email mb-3">
								<label class="sr-only" for="signin-email">Usuario</label>
								<input id="id_username" name="username" type="text" class="form-control signin-email" placeholder="{% translate "Nombre de usuario" %}" required="required">
							</div><!--//form-group-->
							<div class="password mb-3">
								<label class="sr-only" for="signin-password">Contraseña</label>
								<input id="id_password" name="password" type="password" class="form-control signin-password" placeholder="{% translate "Contraseña" %}" required="required">
								<div class="extra mt-3 row justify-content-between">
									<div class="col-6">
										<div class="form-check">
											<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
											<label class="form-check-label" for="RememberPassword">
											{% translate "Recordarme" %}
											</label>
										</div>
									</div><!--//col-6-->
									<div class="col-6">
										<div class="forgot-password text-right">
											<a href="reset-password.html">{% translate "¿Olvidaste tu contraseña?" %}</a>
										</div>
									</div><!--//col-6-->
								</div><!--//extra-->
							</div><!--//form-group-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">{% translate "Ingresar" %}</button>
							</div>
							<input type="hidden" name="next" value="{{next}}"> 
						</form>
						<div class="auth-option text-center pt-5">{% translate "¿No tienes cuenta? ¡Regístrate!" %} <a class="text-link" href="{% url 'usuarios:signup' %}" >{% translate "aquí" %}</a>.</div>
					</div><!--//auth-form-container-->
					<br>
					<br>
					<div class="col">
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input type="hidden" name="text" value="{{redirect_to}}">
							<select class="form-select" name="language" id="">
								{% get_available_languages as LANGUAGES %}
								{% get_language_info_list for LANGUAGES as languages %}
								{% for language in languages %}
									<option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
										{{language.name_local}} ({{language.code}})
									</option>
								{% endfor %}
							</select>
							<br>
							<input type="submit" class="btn app-btn-primary" value="{% translate "Seleccionar idioma" %}">
						</form>
					</div>	
			    </div><!--//auth-body-->
		    		<footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">			    
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    </div><!--//row-->
</body>
</html> 

usuarios/templates/signup.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>{% translate "Registrarse" %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="{% static 'js/all.min.js' %}"></script>
    
    <!-- App CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/portal.css' %}">
</head> 
<body class="app app-signup p-0">    	
    
    <div class="row g-0 app-auth-wrapper">
	    <div class="col-12 col-md-7 col-lg-6 auth-main-col text-center p-5">
		    <div class="d-flex flex-column align-content-end">
			    <div class="app-auth-body mx-auto">	
				    <div class="app-auth-branding mb-4"><a class="app-logo" href="#"><img class="logo-icon mr-2" src="{% static 'favicon.png' %}" alt="logo"></a></div>
					<h2 class="auth-heading text-center mb-4">{% translate "Registro en el Sistema de Videojuegos" %}</h2>					
	
					<div class="auth-form-container text-left mx-auto">
						<form class="auth-form auth-signup-form" method="POST">     
                            {% csrf_token %}  
							<div class="email mb-3">
								<label class="sr-only" for="signup-email">Nombre</label>
								<input id="id_first_name" name="first_name" type="text" class="form-control signup-name" placeholder="{% translate "Nombre" %}" required="required">
							</div>
							<div class="email mb-3">
								<label class="sr-only" for="signup-email">Usuario</label>
								<input id="id_username" name="username" type="text" class="form-control signup-email" placeholder="{% translate "Nombre de usuario" %}" required="required">
							</div>
							<div class="email mb-3">
								<label class="sr-only" for="signup-email">Correo electronico</label>
								<input id="id_email" name="email" type="text" class="form-control signup-email" placeholder="{% translate "Correo electronico" %}" required="required">
							</div>
							<div class="password mb-3">
								<label class="sr-only" for="signup-password">Contraseña</label>
								<input id="id_password" name="password" type="password" class="form-control signup-password" placeholder="{% translate "Crea una contraseña" %}" required="required">
							</div>
							<div class="extra mb-3">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="RememberPassword">
									<label class="form-check-label" for="RememberPassword">
										{% translate "Estoy de acuerdo" %} <a href="#" class="app-link">{% translate "Términos de servicio" %} </a> y <a href="#" class="app-link">{% translate "Política de Privacidad" %}</a>.
									</label>
								</div>
							</div><!--//extra-->
							<div class="text-center">
								<button type="submit" class="btn app-btn-primary btn-block theme-btn mx-auto">{% translate "Registrarse" %}</button>
							</div>
						</form><!--//auth-form-->
						
						<div class="auth-option text-center pt-5">{% translate "¿Ya tienes una cuenta?" %} <a class="text-link" href="{% url 'usuarios:login' %}" >{% translate "Iniciar Sesión" %}.</a></div>
					</div><!--//auth-form-container-->	
					<br>
					<br>
					<div class="col">
						<form action="{% url 'set_language' %}" method="post">
							{% csrf_token %}
							<input type="hidden" name="text" value="{{redirect_to}}">
							<select class="form-select" name="language" id="">
								{% get_available_languages as LANGUAGES %}
								{% get_language_info_list for LANGUAGES as languages %}
								{% for language in languages %}
									<option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
										{{language.name_local}} ({{language.code}})
									</option>
								{% endfor %}
							</select>
							<br>
							<input type="submit" class="btn app-btn-primary" value="{% translate "Seleccionar idioma" %}">
						</form>
					</div>	
				    
			    </div><!--//auth-body-->
		    
			    <footer class="app-auth-footer">
				    <div class="container text-center py-3">
				         <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
			        <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a class="app-link" href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
				       
				    </div>
			    </footer><!--//app-auth-footer-->	
		    </div><!--//flex-column-->   
	    </div><!--//auth-main-col-->
	    <div class="col-12 col-md-5 col-lg-6 h-100 auth-background-col">
		    <div class="auth-background-holder">			    
		    </div>
		    <div class="auth-background-mask"></div>
		    <div class="auth-background-overlay p-3 p-lg-5">
			    <div class="d-flex flex-column align-content-end h-100">
				    <div class="h-100"></div>
				    
				</div>
		    </div><!--//auth-background-overlay-->
	    </div><!--//auth-background-col-->
    
    </div><!--//row-->
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/funciones.js' %}"></script>
</body>
</html> 