usuarios/urls.py
from django.urls import path
# Se importan las vistas a llamar en esta aplicación
# del proyecto 
from . import views
from django.utils.translation import gettext_lazy as _

# Para que las urls puedan tener nombres parecidos 
# sin que haya mezcla de nombres
app_name = 'usuarios'

urlpatterns = [
    path(_('lista/'),views.UsuarioList.as_view(),name='lista'),
    path(_('nuevo/'),views.NuevoUsuario.as_view(), name='nuevo'),
    path(_('editar/<int:pk>'),views.UsuarioActualizar.as_view(),name='editar'),
    path(_('eliminar/<int:pk>'),views.UsuarioEliminar.as_view(),name='eliminar'),
    path(_('ver/<int:pk>'),views.UsuarioDetalle.as_view(),name='ver'),
    path(_('municipios/'),views.obtiene_municipios, name='municipio'),
    path(_('login/'),views.LoginUsuario.as_view(),name='login'),
    path(_('logout/'),views.logout,name='logout'),
    path(_('signup/'),views.SignUpUsuario.as_view(),name='signup'),
    path(_('activar/<slug:uid64>/<slug:token>'),views.ActivarCuenta.as_view(),name='activar'),
    path(_('modificar-grupos/<int:id>'),views.modificar_usuario_grupo,name='modificar_usuario_grupo'),
]

# eliminar/<int:id> Para indicar la recepción de un 
# argumento. Se indica el tipo de dato y el nombre.

ventas/urls.py
from django.urls import path
from . import views
from django.utils.translation import gettext_lazy as _

app_name = 'ventas'

urlpatterns = [
    path(_('carrito'), views.carrito, name='carrito'),
    path(_('eliminar-item/<int:id>'), views.eliminar_item, name='eliminar_item_carrito'),
    path(_('comprar'), views.comprar, name='comprar')
]

videojuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path(_('admin/'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    # Include recibe el nombre de la aplicación .urls
    path(_('categorias/'),include('videojuego.urls_categoria')),
    path(_('videojuegos/'),include('videojuego.urls_videojuego')),
    path(_('usuarios/'),include('usuarios.urls')),
    path(_('articulos/'),include('articulos.urls')),
    path(_('ventas/'),include('ventas.urls')),
]   + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import curp_validator, foto_validator
from django.utils.translation import gettext_lazy as _

class Usuario(User):
    curp = models.CharField(max_length = 18, validators = [curp_validator], blank=True, null=True)
    estado = models.ForeignKey("usuarios.Estado", verbose_name=_("Estado"), on_delete=models.CASCADE, blank=True, null=True)
    municipio = models.ForeignKey("usuarios.Municipio", verbose_name=_("Municipio"), on_delete=models.CASCADE, blank=True, null=True)
    foto = models.ImageField(_("Foto de perfil"), upload_to='perfiles', blank=True, null=True, validators=[foto_validator])

    class Meta:
        verbose_name = _('Usuario')
        verbose_name_plural = _('Usuarios')

class Estado(models.Model):
    nombre = models.CharField(max_length = 50)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Estado')
        verbose_name_plural = _('Estados')

class Municipio(models.Model):
    nombre = models.CharField(max_length=50)
    estado = models.ForeignKey("usuarios.Estado", verbose_name=_("Estado"), on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Municipio')
        verbose_name_plural = _('Municipios')

usuarios/forms.py
from django import forms 
from .models import Usuario
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

class UsuarioForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Usuario
        fields = ('username','password','email','first_name','last_name','curp','estado','municipio','foto')

        widgets = {
            'username' : forms.TextInput(attrs={'class' : 'form-control',
                                                'placeholder' : _('Crea un nombre de usuario')}),
            'password': forms.PasswordInput(attrs={'class': 'form-control',
                                                   'placeholder' : _('Crea una contraseña')}), 
            'email' : forms.EmailInput(attrs={'class' : 'form-control',
                                             'placeholder' : _('Indica tu correo electrónico')}), 
            'first_name' : forms.TextInput(attrs={'class' : 'form-control',
                                                    'placeholder' : _('Indica tu nombre')}),
            'last_name' : forms.TextInput(attrs={'class' : 'form-control',
                                                 'placeholder' : _('Indica tus apellidos')}),  
            'curp' : forms.TextInput(attrs={'class' : 'form-control',
                                            'placeholder' : _('Indica tu CURP')}),                                                                                              
            'estado' : forms.Select(attrs={'class':'form-control'}),
            'municipio' : forms.Select(attrs={'class':'form-control'}),
        }

    # Para guardar la contraseña de forma segura.
    def save(self, commit=True):
        user = super(UsuarioForm,self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

class UsuarioRegistroForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ('username','password')

usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView, View
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth.views import LoginView 
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.core.mail import EmailMessage 
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin
from django.contrib.auth.models import Group
from django.utils.translation import gettext as _
from django.utils.translation import gettext_lazy

from .token import token_activacion
from .models import Usuario, Municipio, Estado
from .forms import UsuarioForm, UsuarioRegistroForm

class NuevoUsuario(PermissionRequiredMixin,CreateView):
    model = Usuario
    form_class = UsuarioForm
    permission_required = 'usuarios.add_usuario'
    extra_context = {'etiqueta' : gettext_lazy('Nuevo'),
    'boton' : gettext_lazy('Agregar'),
    'us_nuevo' : True}                
    success_url = reverse_lazy('usuarios:lista')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Toma el dominio actual. Es muy util para produccion
        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        # Le mandamos las variables requeridas en el formulario
        mensaje = render_to_string('confirmar_cuenta.html',
        {
            'usuario' : user,
            'dominio' : dominio,
            'uid' : uid,
            'token' : token
        }
        )
        asunto = _('Activar cuenta en el Sistema de Videojuegos')
        to = user.email
        # En el to se puede poner una lista de usuarios
        email = EmailMessage(
            asunto,
            mensaje,
            to=[to]
            )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)

class ActivarCuenta(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(kwargs['uid64'])
            token = kwargs['token']
            user = Usuario.objects.get(id=uid)
        except:
            user = None

        if user and token_activacion.check_token(user,token):
            user.is_active = True
            user.save()
            messages.success(self.request,_('¡Cuenta activada con éxito!'))
        else:
            messages.error(self.request,_('Token inválido, contacta al administrador'))
        
        return redirect('usuarios:login')


def obtiene_municipios(request):
    # estado = get_object_or_404(Estado, id=id_estado)
    if request.method == 'GET':
        return JsonResponse({'error':_('Petición incorrecta')}, safe=False, status=403)
    id_estado = request.POST.get('id')
    municipios = Municipio.objects.filter(estado_id=id_estado)
    json = []
    if not municipios:
        json.append({'error' : _('No se encontraron municipios con ese estado')})
    for municipio in municipios:
        json.append({'id' : municipio.id,
                     'nombre' : municipio.nombre})
    return JsonResponse(json, safe=False)

class UsuarioList(PermissionRequiredMixin,ListView):
    paginate_by = 5
    model = Usuario
    permission_required = 'usuarios.view_usuario'
    lista_grupos = Group.objects.all()

    extra_context = {'us_lista' : True,
                     'lista_grupos': lista_grupos}                
    template_name = 'usuarios:lista'

class UsuarioActualizar(PermissionRequiredMixin,UpdateView):
    model = Usuario
    permission_required = 'usuarios.change_usuario'
    form_class = UsuarioForm
    extra_context = {'etiqueta' : gettext_lazy('Editar'),
                     'boton' : gettext_lazy('Guardar')}
    success_url = reverse_lazy('usuarios:lista')

class UsuarioEliminar(PermissionRequiredMixin,DeleteView):
    model = Usuario
    permission_required = 'usuarios.delete_usuario'
    success_url = reverse_lazy('usuarios:lista')

class UsuarioDetalle(PermissionRequiredMixin,DetailView):
    model = Usuario
    permission_required = 'usuarios.view_usuario'

class LoginUsuario(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm
    
    def get_success_url(self):
        self.request.session['articulos'] = {}
        self.request.session['total'] = 0.0
        return super().get_success_url()

class SignUpUsuario(CreateView):
    template_name = 'signup.html'
    form_class = UsuarioForm
    success_url = reverse_lazy('usuarios:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Toma el dominio actual. Es muy util para produccion
        dominio = get_current_site(self.request)
        uid = urlsafe_base64_encode(force_bytes(user.id))
        token = token_activacion.make_token(user)
        # Le mandamos las variables requeridas en el formulario
        mensaje = render_to_string('confirmar_cuenta.html',
        {
            'usuario' : user,
            'dominio' : dominio,
            'uid' : uid,
            'token' : token
        }
        )
        asunto = _('Activar cuenta en el Sistema de Videojuegos')
        to = user.email
        # En el to se puede poner una lista de usuarios
        email = EmailMessage(
            asunto,
            mensaje,
            to=[to]
            )
        email.content_subtype = 'html'
        email.send()

        return super().form_valid(form)

def logout(request):
    auth.logout(request)
    return redirect('usuarios:login')

def modificar_usuario_grupo(request,id):
    grupos = [grupo.id for grupo in Group.objects.all()]
    usuario = Usuario.objects.get(id=id)

    # El usuario tiene por lo menos un grupo asignado dado que en el arreglo
    # viene el token y algún grupo a asignar.
    if len(request.POST) > 1: 
        usuario.groups.clear()
        for item in request.POST:
            if request.POST[item] == 'on':
                usuario.groups.add(Group.objects.get(id=int(item)))
                
        messages.success(request, gettext_lazy(f'Se agregó al usuario {usuario} a los usuarios'))
    # El usuario no tiene ningún grupo asignado
    else:
        messages.error(request, gettext_lazy('El usuario debe pertenecer a un grupo como mínimo'))
    
    return redirect('usuarios:lista')

usuarios/templates/usuarios/usuario_detail.html
{% extends 'dashboard.html' %}
{% load static %}
{% load i18n %}

{% block titulo %}
Detalle del Usuario {{object.username}}
{% endblock titulo %}

{% block contenido %}
    <h1>{% translate "Nombre de usuario" %}: {{object.username}}</h1>
    <h3>{% translate "Nombre" %}: {{object.first_name}}</h3>
    <h3>{% translate "Apellidos" %}: {{object.last_name}}</h3>
    <h3>{% translate "Estado" %}: {{object.estado}}</h3>
    <h3>{% translate "Municipio" %}: {{object.municipio}}</h3>
    <h3>{% translate "Fecha de registro" %}: {{object.date_joined}}</h3>
    {% if object.last_login %}
        <h3>{% translate "Último Inicio de Sesión" %}: {{object.last_login}}</h3>
    {% endif %}
    {% if object.foto %} 
        <h3>{% translate "Foto de perfil" %}:</h3>
        <img height="30%" width="30%" src="{{usuario.foto.url}}">
    {% endif %}
    <p><a href="{% url 'usuarios:lista' %}" class="btn btn-outline-secondary">{% translate "Regresar" %}</a></p>
{% endblock contenido %}

usuarios/templates/usuarios/usuario_form.html
{% extends 'dashboard.html' %}
{% load static %}
{% load i18n %}

{% block titulo %}
{{etiqueta}} {% translate "Usuario" %}
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">{{etiqueta}} {% translate "Usuario" %}</h1>
    <!--La propiedad enctype="multipart/form-data permite que se puedan
    enviar imágenes a través del formulario. -->
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-outline-success">{{boton}}</button>
    </form>
{% endblock contenido %}

{% block js %}
    <script src="{% static 'js/funciones.js' %}"></script>
{% endblock js %}

    

usuarios/templates/usuarios/usuario_list.html
{% extends 'dashboard.html' %}
{% load static %}
{% load i18n %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/extra.css' %}">
{% endblock %}

{% block titulo %}
    {% translate "Lista de Usuarios" %}
{% endblock titulo %}

{% block contenido %}
<h1 class="app-page-title">{% translate "Lista de Usuarios" %}</h1>
<div class="app-card app-card-orders-table shadow-sm mb-5">
  {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}success{% endif %}">
          {{message}}
        </div>
    {% endfor %}
  {% endif %}
  <table class="table table-hover">
    <thead>
        <th>{% translate "Foto" %}</th>
        <th>{% translate "Nombre de usuario" %}</th>
        <th>{% translate "Nombre" %}</th>
        <th>{% translate "Apellido" %}</th>
        <th>{% translate "Estado" %}</th>
        <th>{% translate "Municipio" %}</th>
        <th>{% translate "Acciones" %}</th>
    </thead>
    <tbody>
      <!--Se pone 'object_list' porque así lo maneja el
      Framerowk si no lo cambiamos -->
      {% for usuario in object_list %}
      <tr>
          <td>
            {% if usuario.foto %}
              <img src="{{MEDIA_URL}}{{usuario.foto}}" alt="" width="40px">
            {% else %}
              <img src="{% static 'images/nouser.png' %}" alt="" width="40px">
            {% endif %}
          </td>
          <td>{{usuario.username}}</td>
          <td>{{usuario.first_name}}</td>
          <td>{{usuario.last_name}}</td>
          <td>{{usuario.estado}}</td>
          <td>{{usuario.municipio}}</td>
          <td>
            <a href="{% url 'usuarios:ver' usuario.id %}" class="btn btn-outline-info">{% translate "Ver" %}</a>
            <a href="{% url 'usuarios:editar' usuario.id %}" class="btn btn-outline-warning">{% translate "Editar" %}</a>
            <button onclick="muestraModal('{% url 'usuarios:eliminar' usuario.id %}','el Usuario {{usuario.username}}')" type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#eliminarModal">{% translate "Eliminar" %}</button>
            <a href="#" class="btn btn-outline-success">{% translate "Activar" %}</a>
            <button id="usuarioGrupo" onclick="muestraModalGrupos('{% url 'usuarios:modificar_usuario_grupo' usuario.id %}','{% for g in usuario.groups.all %}{{g.id}}-{% endfor %}')" type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#gruposModal">{% translate "Grupos" %}</button>
          </td>
        </tr>
          {% endfor %}
    </tbody>
  </table>
</div>  

<!--Paginator-->
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">{% translate "Previo" %}</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">{% translate "Previo" %}</a>
      </li>
    {% endif %}
    {% for num_page in page_obj.paginator.page_range  %}
      {% if num_page == page_obj.number %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ num_page }}">{{num_page}}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num_page }}">{{num_page}}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{% translate "Siguiente" %}</a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#">{% translate "Siguiente" %}</a>
    </li>
    {% endif %}
  </ul>
</nav>

<!-- Modal -->
<div class="modal fade" id="eliminarModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% translate "Eliminando Registro"  %}</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modalCuerpo">
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{% translate "No" %}</button>
          <form id="formEliminar" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-danger">{% translate "Sí, estoy seguro" %}</button>
          </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal Grupos -->
<div class="modal fade" id="gruposModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% translate "Asignación de Grupos" %}</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modalCuerpoGrupos">
        <form id="formGrupos" method="POST">
          <table class="table">
            <thead>
              <th>{% translate "Nombre del grupo" %}</th>
              <th>{% translate "Habilitado" %}</th>
            </thead>
            <tbody>
              <div id="permisosAsignados">
                {% for grupo in lista_grupos %}
                  <tr>
                    <td>{{grupo}}</td>
                    <td>
                      <label class="switch" >
                        <input type="checkbox" name='{{grupo.id}}'>
                        <span class="slider round"></span>
                      </label>                  
                    </td>
                  </tr>  
                {% endfor %}
              </div>
            </tbody>
          </table>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">{% translate "Descartar cambios" %}</button>
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-success">{% translate "Guardar cambios" %}</button>
          </form>
      </div>
    </div>
  </div>
</div>

{% endblock contenido %}

{% block js %}
  <script src="{% static 'js/funciones.js' %}"></script>
{% endblock js %}